#!/bin/sh

# Compositor
picom --config ~/.config/picom/picom.conf &

# Barra
polybar example &

# Lanzador de atajos
sxhkd &

# Fondo de pantalla
feh --bg-scale ~/Imágenes/fondo.png &

# Configuración de escritorios
bspc monitor -d I II III IV V VI VII VIII IX X

# Bordes y gaps
bspc config border_width         2
bspc config window_gap           10
bspc config focused_border_color "#89b4fa"
bspc config normal_border_color  "#1e1e2e"

exec bspwm
