sudo pacman -S xorg --noconfirm
sudo pacman -S xf86-video-intel --noconfirm
sudo pacman -S mesa --noconfirm
sudo pacman -S xdg-user-dirs --noconfirm
sudo pacman -S xorg-xinit --noconfirm
sudo pacman -S git --noconfirm
sudo pacman -S alacritty --noconfirm
sudo pacman -S flameshot --noconfirm
sudo pacman -S mpv --noconfirm
sudo pacman -S emacs --noconfirm
sudo pacman -S bspwm --noconfirm
sudo pacman -S sxhkd --noconfirm
sudo pacman -S feh --noconfirm
sudo pacman -S picom --noconfirm
sudo pacman -S ranger --noconfirm
sudo pacman -S arandr --noconfirm
sudo pacman -S ark --noconfirm
sudo pacman -S bluez --noconfirm
sudo pacman -S bluez-utils --noconfirm
sudo pacman -S brightnessctl --noconfirm
sudo pacman -S rofi --noconfirm
sudo pacman -S dunst --noconfirm
sudo pacman -S htop --noconfirm
sudo pacman -S ntfs-3g --noconfirm
sudo pacman -S obsidian --noconfirm
sudo pacman -S openssh --noconfirm
sudo pacman -S openssl --noconfirm
sudo pacman -S pulseaudio --noconfirm
sudo pacman -S pulseaudio-alsa --noconfirm
sudo pacman -S pulseaudio-bluetooth --noconfirm
sudo pacman -S stunnel --noconfirm
sudo pacman -S telegram-desktop --noconfirm
sudo pacman -S thunar --noconfirm
sudo pacman -S unzip --noconfirm
sudo pacman -S zsh --noconfirm
sudo pacman -S yt-dlp --noconfirm
sudo pacman -S thunar-volman --noconfirm
sudo pacman -S thunar-archive-plugin --noconfirm
sudo pacman -S ripgrep --noconfirm
sudo pacman -S fd --noconfirm
sudo pacman -S npm --noconfirm
sudo pacman -S noto-fonts-emoji --noconfirm
